
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1.compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Simbolo = 16;
  public static final int Complemento = 14;
  public static final int ParentesisCerrar = 11;
  public static final int Union = 12;
  public static final int Diferencia = 15;
  public static final int ID = 17;
  public static final int Coma = 7;
  public static final int PuntoYComa = 6;
  public static final int Interseccion = 13;
  public static final int EOF = 0;
  public static final int LlaveCerrar = 9;
  public static final int Notacion = 5;
  public static final int Flecha = 4;
  public static final int error = 1;
  public static final int LlaveAbrir = 8;
  public static final int Reservada = 2;
  public static final int ParentesisAbrir = 10;
  public static final int DosPuntos = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Reservada",
  "DosPuntos",
  "Flecha",
  "Notacion",
  "PuntoYComa",
  "Coma",
  "LlaveAbrir",
  "LlaveCerrar",
  "ParentesisAbrir",
  "ParentesisCerrar",
  "Union",
  "Interseccion",
  "Complemento",
  "Diferencia",
  "Simbolo",
  "ID"
  };
}

